apiVersion: apps/v1
kind: Deployment
metadata:
  name: eros-template
  labels:
    app: eros-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eros-template
  template:
    metadata:
      labels:
        app: eros-template
    spec:
      containers:
        - name : main
          image: eros-template
          imagePullPolicy: Always

